DELETE FROM USERS;

INSERT INTO USERS (ID,EMAIL, PASSWORD, ROLE)
VALUES (DEFAULT ,'admin@gmail.com', '$2a$10$u/PP688XO9Giezr4/RFZT.rua.t1H2ZcP74fBmjBFszEqbP.nYS.e', 'ADMIN');

INSERT INTO USERS (EMAIL, PASSWORD, ROLE)
VALUES ('user@gmail.com', '$2a$10$arAXFp.OY1WzRmEGyoovz.CLPSl/gWDxJXPDcir1mg1jBrP.lsHam', 'USER');