DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS RESTAURANTS;
DROP TABLE IF EXISTS MEALS;
DROP TABLE IF EXISTS MENU;
DROP TABLE IF EXISTS VOTES;

CREATE TABLE USERS (
  ID       IDENTITY PRIMARY KEY,
  EMAIL    VARCHAR NOT NULL,
  PASSWORD VARCHAR NOT NULL,
  ROLE     VARCHAR NOT NULL
);

CREATE TABLE RESTAURANTS (
  ID      IDENTITY PRIMARY KEY,
  NAME    VARCHAR NOT NULL,
  ADDRESS VARCHAR
);

CREATE TABLE MEALS (
  ID   IDENTITY PRIMARY KEY,
  NAME VARCHAR NOT NULL
);

CREATE TABLE MENU (
  ID            IDENTITY PRIMARY KEY,
  DATE          DATE NOT NULL,
  RESTAURANT_ID INTEGER   NOT NULL,
  MEAL_ID       INTEGER   NOT NULL,
  price         DECIMAL(20, 2),
  FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (ID) ON DELETE CASCADE,
  FOREIGN KEY (MEAL_ID) REFERENCES MEALS (ID) ON DELETE CASCADE
);

CREATE TABLE VOTES (
  ID            IDENTITY PRIMARY KEY,
  DATE          TIMESTAMP NOT NULL,
  USER_ID INTEGER   NOT NULL,
  RESTAURANT_ID INTEGER   NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
  FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (ID) ON DELETE CASCADE
);