DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS RESTAURANTS;
DROP TABLE IF EXISTS MEALS;
DROP TABLE IF EXISTS MENU;
DROP TABLE IF EXISTS VOTES;

DROP SEQUENCE IF EXISTS global_seq;

CREATE SEQUENCE global_seq START WITH 100001 INCREMENT BY 1;

CREATE TABLE USERS (
  ID       BIGINT DEFAULT NEXTVAL('global_seq') PRIMARY KEY,
  EMAIL    VARCHAR NOT NULL,
  PASSWORD VARCHAR NOT NULL,
  ROLE     VARCHAR NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx
  ON USERS (email);

CREATE TABLE RESTAURANTS (
  ID      BIGINT DEFAULT NEXTVAL('global_seq') PRIMARY KEY,
  NAME    VARCHAR NOT NULL,
  ADDRESS VARCHAR
);

CREATE TABLE MEALS (
  ID   IDENTITY PRIMARY KEY,
  NAME VARCHAR NOT NULL
);

CREATE TABLE MENU (
  ID            BIGINT DEFAULT NEXTVAL('global_seq') PRIMARY KEY,
  DATE          TIMESTAMP NOT NULL,
  RESTAURANT_ID INTEGER   NOT NULL,
  MEAL_ID       INTEGER   NOT NULL,
  price         DECIMAL(20, 2),
  FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (ID) ON DELETE CASCADE,
  FOREIGN KEY (MEAL_ID) REFERENCES MEALS (ID) ON DELETE CASCADE
);

CREATE TABLE VOTES (
  ID            BIGINT DEFAULT NEXTVAL('global_seq') PRIMARY KEY,
  DATE          TIMESTAMP NOT NULL,
  USER_ID       INTEGER   NOT NULL,
  RESTAURANT_ID INTEGER   NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
  FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (ID) ON DELETE CASCADE
);